# Assignment

Import numpy as np

In [4]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [5]:
l=list(range(1,6))
l=np.array(l)
l

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [6]:
m=[[1,2,3],[4,5,6],[7,8,9]]
m=np.array(m)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [7]:
n=np.arange(1,18,2).reshape(3,3)
n

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [10]:
np.random.randint(0,10,10)

array([2, 4, 1, 3, 6, 5, 7, 2, 4, 0])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [15]:
o=np.arange(1,6).reshape(5,1)
o

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [16]:
o.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [28]:
p=np.arange(1,11)
print(p[2])
print(p[3])
print(p[-2])

3
4
9


Print alternate elements of that array

In [29]:
for i in range(0,10,2):
    print(p[i])

1
3
5
7
9


Change last 3 elements into 100 using broadcasting and print

In [30]:
p[-3:]=100
for i in range(0,10):
    print(p[i])

1
2
3
4
5
6
7
100
100
100


Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [5]:
z=np.arange(1,26).reshape(5,5)
z[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])